import { Container, VStack } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import AuthButton from "../features/home/components/AuthButton"
import EntryEditorButton from "../features/home/components/EntryEditorButton"
import Title from "../features/home/components/Title"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Title />
          <VStack mt={16} gap={6}>
            <EntryEditorButton />
            <AuthButton />
          </VStack>
        </Container>
      </main>
    </div>
  )
}

export default Home
